Completed project
Lizdev-05/capstone-project pull request #41
Opened 2022-07-29 14:48 UTC by Lizdev-05

In this milestone, @Lizdev-05  and  @stephnna  worked and achieved the following...
Video Link : (https://drive.google.com/file/d/1fTzlTIVfKIMp4r3HL0fPUA_81b_b5TkL/view)
- Get a list of items with a unique item id (or generate the unique id).

- For a given item, get detailed information about it.

- When the page loads, the web app retrieves data from the selected API and shows the list of items on the screen.

- Used the Involvement API to show the item likes.

- When the user clicks on the Like button of an item, the interaction is recorded in the Involvement API and the screen is updated.

- When the user clicks on the "Comments" button, the Comments popup appears.

- When the popup loads, the web app retrieves data from the selected API and shows details about the selected item.

- The Involvement API shows the item comments.

- When the user clicks on the "Comment" button, the data is recorded in the Involvement API and the screen is updated.

- We have counters in all the interfaces that show:
    The number of items (home).
   The number of comments (comments popup).

2022-07-29 17:02 UTC, medaminedev66 requested changes
Hi @Lizdev-05 and @stephnna  😃, :wave:, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- The repo looks professional
- GitFlow best practices have been followed
- There are no linter errors
- You have a descriptive PR
- Your design looks nice
- Your code organization was great
- Your web app runs without errors

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-29 17:02 UTC, medaminedev66 commented on src/modules/likeCounter.js
> +};
- [ ] Please, instead of using Promises (then), try to use async and await to send and receive the data as per project requirements.

2022-07-29 17:02 UTC, medaminedev66 commented on src/index.js
> +likes();
- [ ] When the page loads, the web app should show the number of likes for each item. When I open the home page, I can see only 0 likes below each item. The number of likes was shown after clicking on the like button. Please work on that.

2022-07-29 17:16 UTC, Lizdev-05 commented on src/modules/likeCounter.js
> +};
Hello @medaminedev66, I saw your review but, we are actually allowed to use call back and promises. I will work on the like counter that you talk about. Thank you. [the project recruirement](https://github.com/microverseinc/curriculum-javascript/blob/main/group-capstone/js_capstone.mdl).

2022-07-29 17:54 UTC, medaminedev66 commented on src/modules/likeCounter.js
> +};
Hi, @medaminedev66. Following the project requirements, you have to use async and await. You are not allowed to use promises. 

<img width="441" alt="image" src="https://user-images.githubusercontent.com/77190203/181817101-fcc6b8c1-8201-49a6-a0b2-c0318446fbcc.png">

2022-07-29 18:54 UTC, Danieldotcomcoder approved these changes
Hello @Lizdev-05  &  @stephnna, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 👍 👍 😄 👏 

Congratulations! 🎉 🎉 🎉 

## Highlights
- Professional Readme File ✔✔
- Linters are setup correctly ✔✔
- Clear and nice code ✔✔

![comp-2](https://user-images.githubusercontent.com/87448628/159119684-e86473c4-9b60-43a3-90f2-54048e841394.gif)
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-29 18:59 UTC, merged

2022-09-20 21:10 UTC, Lizdev-05 commented on src/modules/likeCounter.js
> +};
Okay, thank you for calling our attention to the errors. We will work on them.

2022-09-20 21:10 UTC, Lizdev-05 commented on src/index.js
> +likes();
Okay, we will check it out.

2022-09-20 21:10 UTC, Lizdev-05 commented
Thanks for reviewing and approving my project, I appreciate it.